### ISSUE TITLE
Feature: User can sign up and login

### ISSUE THREAD

**Issue by timlee712** [timlee712/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up and login

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to sign up by creating a username and password

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-04-17 at 9 12 39 AM](https://user-images.githubusercontent.com/121835590/232546450-bf248cb3-54a6-4476-abe2-f94cd9f44af1.png)
![Screenshot 2023-04-17 at 9 13 15 AM](https://user-images.githubusercontent.com/121835590/232546453-e5dc8bdc-107e-49ae-b640-f1f73db6beb3.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to have a sign up page
- [ ] 
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
